/* Auto-generated by genmsg_cpp from file /Volumes/SD/Git/PX4/Firmware_fmuv2/Firmware/msg/actuator_armed.msg */


#pragma once

#include <stdint.h>
#ifdef __cplusplus
#include <cstring>
#else
#include <string.h>
#endif

#include <nuttx/uorbc/uORB.h>


#ifndef __cplusplus

#endif


#ifdef __cplusplus
struct test2_s {
#else
struct test2_s {
#endif
	uint64_t timestamp; // required for logger
	uint64_t magnetometer_timestamp;
	uint64_t baro_timestamp;
	uint64_t rng_timestamp;
	uint64_t flow_timestamp;
	uint64_t asp_timestamp;
	uint64_t ev_timestamp;
	uint32_t seq;
	uint64_t time_usec;
	float gyro_integral_dt;
	float accelerometer_integral_dt;
	float gyro_rad[3];
	float accelerometer_m_s2[3];
	float magnetometer_ga[3];
	float baro_alt_meter;
	int32_t lat;
	int32_t lon;
	int32_t alt;
	float eph;
	float epv;
	float sacc;
	float vel_m_s;
	float vel_n_m_s;
	float vel_e_m_s;
	float vel_d_m_s;
	float range_to_ground;
	float flow_pixel_integral[2];
	float flow_gyro_integral[2];
	uint32_t flow_time_integral;
	float indicated_airspeed_m_s;
	float true_airspeed_m_s;
	float pos_ev[3];
	float quat_ev[4];
	float pos_err;
	float ang_err;
	uint8_t fix_type;
	uint8_t nsats;
	bool vel_ned_valid;
	uint8_t flow_quality;

#ifdef __cplusplus

#endif
};

/* register this as object request broker structure */
ORB_DECLARE(test2);


