/* Auto-generated by genmsg_cpp from file /Volumes/SD/Git/PX4/Firmware_fmuv2/Firmware/msg/actuator_armed.msg */

#include "../topics_inc/topic_test2.h"

const char *__orb_test2_fields = "uint64_t timestamp;uint64_t magnetometer_timestamp;uint64_t baro_timestamp;uint64_t rng_timestamp;uint64_t flow_timestamp;uint64_t asp_timestamp;uint64_t ev_timestamp;uint64_t time_usec;float gyro_integral_dt;float accelerometer_integral_dt;float[3] gyro_rad;float[3] accelerometer_m_s2;float[3] magnetometer_ga;float baro_alt_meter;int32_t lat;int32_t lon;int32_t alt;float eph;float epv;float sacc;float vel_m_s;float vel_n_m_s;float vel_e_m_s;float vel_d_m_s;float range_to_ground;float[2] flow_pixel_integral;float[2] flow_gyro_integral;uint32_t flow_time_integral;float indicated_airspeed_m_s;float true_airspeed_m_s;float[3] pos_ev;float[4] quat_ev;float pos_err;float ang_err;uint8_t fix_type;uint8_t nsats;bool vel_ned_valid;uint8_t flow_quality;";

ORB_DEFINE(test2, struct test2_s, 224,
    __orb_test2_fields);


