/* Auto-generated by genmsg_cpp from file /Volumes/SD/Git/PX4/Firmware_fmuv2/Firmware/msg/actuator_armed.msg */

#include "../topics_inc/topic_test5.h"

const char *__orb_test5_fields = "uint64_t timestamp;uint32_t seq;uint8_t[4] _padding0;";

ORB_DEFINE(test5, struct test5_s, 12,
    __orb_test5_fields);


